In [1]:
import pandas as pd

df = pd.read_csv('gold_prices_2000_2026_feb.csv')

In [2]:
df.head()

         Date  Gold_Price_USD_YFinance
0  2000-08-01               276.099991
1  2000-09-01               273.389996
2  2000-10-01               269.809090
3  2000-11-01               265.874997
4  2000-12-01               271.515005

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307 entries, 0 to 306
Data columns (total 2 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Date                     307 non-null    object
 1   Gold_Price_USD_YFinance  307 non-null    float64
dtypes: float64(1), object(1)
memory usage: 4.9+ KB

In [4]:
df.describe(include='all')

              Date  Gold_Price_USD_YFinance
count          307               307.000000
unique         307                      NaN
top     2000-08-01                      NaN
freq             1                      NaN
mean           NaN              1268.912767
std            NaN               781.063844
min            NaN               261.079997
25%            NaN               644.017821
50%            NaN              1244.881819
75%            NaN              1681.497146
max            NaN              4815.533366

In [5]:
df.isnull().sum()

Date                       0
Gold_Price_USD_YFinance    0
dtype: int64

In [6]:
# Converting the Date column to datetime
df['date'] = pd.to_datetime(df['Date'])

# Rounding of the gold price
df['Gold_Price_USD_YFinance'] = df['Gold_Price_USD_YFinance'].round(2)

# definition of Date as a temporal index
df.set_index('Date', inplace=True)

In [7]:
# Renaming of columns
df = df.rename(columns={'Date': 'date', 'Gold_Price_USD_YFinance': 'gold_price_usd'})

In [8]:
# Create of columns(Feature engineering)
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['year_month'] = df['date'].dt.to_period('M').astype(str)
df['decade'] = (df['year'] // 10) * 10
df['period_type'] = df['decade'].astype(str) + 's'

In [9]:
df.head()

,gold_price_usd,date,year,month,year_month,decade,period_type
Date,,,,,,,
2000-08-01,276.10,2000-08-01,2000,8,2000-08,2000,2000s
2000-09-01,273.39,2000-09-01,2000,9,2000-09,2000,2000s
2000-10-01,269.81,2000-10-01,2000,10,2000-10,2000,2000s
2000-11-01,265.87,2000-11-01,2000,11,2000-11,2000,2000s
2000-12-01,271.52,2000-12-01,2000,12,2000-12,2000,2000s

In [10]:
# Reasoned removal of the variables not retained
df = df.drop(columns=['month'])

In [11]:
# convert to excel
df.to_excel("gold_price_2000_2026_feb.xlsx",index=False,sheet_name="gold_price_2000_2026_feb")

In [12]:
df.head()

            gold_price_usd       date  year year_month  decade period_type
Date
2000-08-01          276.10 2000-08-01  2000    2000-08    2000       2000s
2000-09-01          273.39 2000-09-01  2000    2000-09    2000       2000s
2000-10-01          269.81 2000-10-01  2000    2000-10    2000       2000s
2000-11-01          265.87 2000-11-01  2000    2000-11    2000       2000s
2000-12-01          271.52 2000-12-01  2000    2000-12    2000       2000s

In [18]:
# Connect to sql
from sqlalchemy import create_engine
from urllib.parse import quote_plus

user = "root"
password = "mysql2026"
host = "localhost"
port = 3306
db = "esmel"

engine = create_engine(
    f"mysql+pymysql://{user}:{password}@{host}:{port}/{db}",
    echo=False
)

In [19]:
engine.connect()

In [20]:
df.to_sql(
    name="gold_price_2000_2026",
    con=engine,
    if_exists="replace",
    index=False
)

307